### PR TITLE
click-drop mechanics (and other stuff)

### PR DESCRIPTION
**Pull request by nnickoloff1234**
Mainly improvements for https://github.com/gbtami/pychess-variants/issues/5

But also some other stuff like predrop logic for all drop variants and some small fixes related to pre-drop and maybe some other small fixes i am forgetting right now

Should be merged together with the corresponding PR from pychess-variants: https://github.com/gbtami/pychess-variants/pull/584

### CODE REVIEW

**Comment by gbtami** [comment]
After quick look it seems OK. Shinobi and Synochess are missing from predrop.ts

**Comment by nnickoloff1234** [comment]
> Shinobi and Synochess are missing from predrop.ts  

strange how i've missed them. i will take a look later today

**Comment by gbtami** [comment]
Thx! I will wait for @Fulmene review before merge. It may take some time. Maybe next week.

**Comment by nnickoloff1234** [comment]
> Thx! I will wait for @Fulmene review before merge. It may take some time. Maybe next week.

Great! I'm open to any feedback so don't try to spare my feelings :) 
That's pretty much my first typescript code ever.

**Review by Fulmene — CHANGES_REQUESTED** [review]

**Review by Fulmene — APPROVED** [review]

**Comment by gbtami** [comment]
Thx a lot!

**Pull request merged**
